### ISSUE TITLE
Wait, Really? Github is fucking blocked in Iran now?

### ISSUE THREAD

**Issue by aaomidi** [pi0/github-is-blocked-in-iran#4]
Honestly, the best way to go about this is a twitter campaign from developers on Twitter.

We could all retweet a tweet to Rouhani.

**Comment by pi0** [comment]
@aaomidi GitHub itself is open! (hopefully it remains :D) But one important sub-domain `raw.githubusercontent.com` which is used for delivering images, view raw source code and for many scripts to downloading partial content from GitHub repositories is blocked.

**Comment by pi0** [comment]
PS: We have started reporting this in *peyvandha.ir* and many people complained  about it in recent months in twitter, etc.

**Comment by aaomidi** [comment]
Yeah but that's not as public of an outrage. Github is used by many startups in Iran.

And the problem with them just reversing this decision isn't something we should settle for. There are CI systems running off of github that go haywire when this kind of stupid stuff happens.

**Comment by pi0** [comment]
Our CI which was using npm git dependencies (`owner/project`) was broken! Some people where using `hosts` file to bypass this censorship. As of 1 months ago they even hardened it. I would be happy to follow any steps you suggest in order to white-list this domain again.

**Comment by pi0** [comment]
![image](https://cloud.githubusercontent.com/assets/5158436/26498250/a205d67c-4243-11e7-944e-df44c921aed0.png)

This ticket is open for more than 1 month without any response ...

**Comment by aaomidi** [comment]
This is ridiculous.

I sent a tweet out to the president. The more people talking about this on twitter, the higher a chance we get to resolve this.

https://twitter.com/aaomidi/status/868110559316774913

**Comment by aaomidi** [comment]
For people who find this comment thread, I recommend taking a look at DNSCrypt. 

https://dnscrypt.org/

It encrypts your DNS requests to get around this stupid block.

**Comment by pi0** [comment]
@aaomidi DNS workarounds are no longer working :)) They are using DPI to completely make **target ips** inaccessible. Also have to remove that unreasonable censorship not bypassing it.

**Comment by aaomidi** [comment]
*sigh*

This is ridiculous. It seems like they're using SNI fields to block sites too now.

**Comment by XiaoNode** [comment]
wow,it's to bad, China is blocked google and facebook... it's more bad than iran

**Comment by nerdy-panda** [comment]
:\
iran :\ 
Sanctions are not important :\ 
we have security :\ 
:| ha ha ha :|

**Comment by 0x416c69** [comment]
Now it's the other way around.
Iran is blocked in GitHub 🤣 
![image](https://user-images.githubusercontent.com/10671711/61863091-32d35d00-aee4-11e9-9f6e-e2c4cc744a73.png)

**Comment by peymangoly** [comment]
Better to send tweet to Azari Jahromi the minister of IT. He is in charge of filtering.

**Comment by MatinSasan** [comment]
To support: https://github.com/1995parham/github-do-not-ban-us  

To read:  https://medium.com/@hamed/github-blocked-my-account-and-they-think-im-developing-nuclear-weapons-e7e1fe62cb74

**Comment by 0x416c69** [comment]
@peymangoly raw.githubusercontent.com is no more censored and I'm sure Mr Jahromi isn't in charge of GitHub and U.S. sanctions.

People are already burning in their daily living in Iran, the life cost, the censorship from inside, the blocking from outside, low paycheck, I'm sure GitHub is the least of this so don't give yourselves hope on this guys, better start using self-hosted GitLab.

**Comment by buhtz** [comment]
You could use [Codeberg](https://codeberg.org/) as an independend alternative to GitHub, GitLab and Co.

**Comment by 0x416c69** [comment]
God bless Gitea, what would you do without them? At least don't modify and remove copyrights.
